[package]
name = "g_calc"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A small utility for performing simple math calculations using infix expression"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


